name: Validate Next.js project

on:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: yarn
        
      - name: Run Lint
        run: yarn lint
